[project]
name = "spotify-share-library"
version = "0.2.1"
description = "Keep user's library synced with a shareable playlist on Spotify"
authors = [{name = "Francesco Frassinelli", email = "fraph24@gmail.com"}]
requires-python = ">=3.14"
dependencies = [
    "django-environ>=0.12",
    "spotipy>=2.26.0",
    "uvicorn>=0.34",
    "starlette>=0.46",
]

[dependency-groups]
dev = [
    "prek>=0.3",
]

